services:
  backend:
    build: .
    container_name: fastapi_app
    # network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./env/backend/.env
    volumes:
      - ./backend:/app/backend

  redis:
      image: redis/redis-stack-server:latest
      container_name: redis_stack
      restart: always
      env_file:
        - ./env/backend/.env
      ports:
        - "${REDIS_PORT:-6379}:6379"
      volumes:
        - redis_data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      # Simplified command: just the binary and the config file path
      command: ["redis-stack-server", "/usr/local/etc/redis/redis.conf"]
volumes:
  redis_data: